# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FridgeKeeper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FridgeKeeper

  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'GoogleAPIClientForREST/Sheets'
end
